### ISSUE TITLE
I got an error: 'h' must be in scope when using JSX

### ISSUE THREAD

**Issue by rafi16jan** [just-boris/create-react-app#38]
I got an error: 'h' must be in scope when using JSX

I'm manually tweaking react dependency from a react template and got this. What should I do?

**Comment by rafi16jan** [comment]
Adding import h from 'preact' fix the issue but I don't want import it at every file. How can I resolve this?

**Comment by just-boris** [comment]
Hello! 
`h` is used in Preact as an analog of the `React.createElement` method from React. It is needed to make your JSX constructions work.

It is not possible to use JSX without importing this symbol, this is similar to the original React approach. You have to always import `React` in your files with JSX, even if you do not use it directly, for instance in functional components: https://stackoverflow.com/questions/44141010/do-i-need-to-import-react-for-stateless-functional-components/44141043
